synology:
  url: "http://192.168.1.3:5000"
  username: "bot"
  password: ""  # замените на реальный пароль
  
  # Маппинг категорий на пути в Download Station
  paths:
    movie: "/downloads/movie"
    cartoon: "/downloads/cartoons"
    shows: "/downloads/shows"
    audiobook: "/downloads/audiobooks"
    other: "/downloads/other"
    shows_cartoons: "/downloads/shows_cartoons"

debug: true
